console.log("TypeScript Number Properties:")
console.log("Maximum value that a number variable can hold: " + Number.MAX_VALUE)
console.log("Minimum value that a number variable can hold: " + Number.MIN_VALUE)
console.log("Positive Infinity value that a number variable can hold: " + Number.POSITIVE_INFINITY)
console.log("Negative Infinity value that a number variable can hold: " + Number.NEGATIVE_INFINITY)
